export const ErrorCodeEnum = {
  // Auth
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",
  ACCESS_DENIED: "ACCESS_DENIED",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Resource
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",

  // File upload
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",

  DOCUMENT_NOT_READY: "DOCUMENT_NOT_READY",
  DOCUMENT_PROCESSING_FAILED: "DOCUMENT_PROCESSING_FAILED",

  // System
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCodeEnumType = (typeof ErrorCodeEnum)[keyof typeof ErrorCodeEnum];